Use flags to enable/disable features
Tetrax-10/tails-tweaks pull request #1
Opened 2024-08-26 14:09 UTC by nsa-yoda

Creates flags to enable/disable features by setting them to true/false, allowing for easier configuration of features that a user might want. 

Also moves magic values to variables (like the wallpaper path, mouse speed, etc)

<img width="692" alt="Screenshot 2024-08-26 at 10 08 17 AM" src="https://github.com/user-attachments/assets/0fece362-e61f-44c6-a196-00f91a8c425b">

2024-08-26 16:30 UTC, Tetrax-10 requested changes
Hey thanks for the PR, really nice one.

Please review the requested changes.

2024-08-26 16:30 UTC, Tetrax-10 commented on configure.sh
> +dark_terminal=true
`dark_terminal` option is not necessary merge it with `dark_mode`.

2024-08-26 16:30 UTC, Tetrax-10 commented on configure.sh
> +  gsettings set org.gnome.desktop.screensaver lock-enabled false
why using `dim_screen` variable for this? shouldn't you be using something like `auto_screen_lock`?

2024-08-26 16:30 UTC, Tetrax-10 commented on configure.sh
> +disable_usb_auto_mount=false
the default value of `disable_usb_auto_mount` should be `true`.

2024-08-26 23:29 UTC, Tetrax-10 requested changes
I think everything is fine except these two minor changes.

2024-08-26 23:29 UTC, Tetrax-10 commented on README.md
> +| Disable Wi-Fi            | `disable_wifi`             | `false`       | Optionally disables Wi-Fi.                          |
```suggestion
| Disable Wi-Fi            | `disable_wifi`             | `false`       | Disables Wi-Fi.                          |
```

2024-08-26 23:29 UTC, Tetrax-10 commented on .gitignore
> +.idea
`.gitignore` is not needed. Let the repo be simple with only required files.

```suggestion
```

2024-08-27 16:55 UTC, Tetrax-10 commented
I think I wasn't that clear. We don't need `.gitignore` file. Can you delete that file and commit?

2024-08-27 19:36 UTC, nsa-yoda commented
> I think I wasn't that clear. We don't need `.gitignore` file. Can you delete that file and commit?

Ah not sure why the previous commit from your comment didn't apply. Updating.

2024-08-28 00:47 UTC, Tetrax-10 approved these changes

2024-08-28 00:49 UTC, merged